apiVersion: apps/v1
kind: Deployment
metadata:
  name: sendmessage-deployment
  labels:
    app: sendmessage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sendmessage
  template:
    metadata:
      labels:
        app: sendmessage
    spec:
      containers:
      - name: sendmessage
        image: sting672744/sendmessage:1.0
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: sendmessage-service
spec:
  type: NodePort
  selector:
    app: sendmessage
  ports:
    - protocol: TCP
      port: 30100
      targetPort: 8080
      nodePort: 30100